Music.Web/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Music.Contexto;
using Music.Dominio;

namespace Music.Web.Controllers
{
    public class AlbumController : Controller
    {

        AlbumDao dao = new AlbumDao();

        // GET: Album
        public ActionResult Index()
        {
            var album = dao.BuscarTodos();
            return View(album);
        }
        public ActionResult Adicionar()
        {
            ArtistaDao artistaDao = new ArtistaDao();
            ViewBag.ArtistaID = new SelectList(artistaDao.BuscarTodos(), "ArtistaID", "Nome");
            return View();
       }
        [HttpPost]
        public ActionResult Adicionar(Album album)
        {
            if (album.ArtistaId>0)
            {
                dao.Salvar(album);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Index");
            }
           
        }
        public ActionResult Editar(int id)
        {
            var album = dao.BuscarPorId(id);
            ArtistaDao artistaDao = new ArtistaDao();
            var artista = artistaDao.BuscarTodos();

            ViewBag.ArtistaID = new SelectList(artista, "ArtistaID", "Nome", album.ArtistaId);

            return View(album);

        }
        [HttpPost]
        public ActionResult Editar(Album album)
        {
            if (!string.IsNullOrEmpty(album.Titulo))
            {
                dao.SalvarAlteracao(album);
                
                return RedirectToAction("Index");
            }

            return View(album);
        }

        //Método para excluir uma artista
        [HttpPost]
        public void Deletar(int id)
        {
            try
            {
                bool TrueOrFalse = dao.Excluir(id);

            }
            catch (Exception)
            {
                
                throw;
            }
        }


    }
    
}

Music.Web/Controllers/ArtistaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Music.Contexto;
using Music.Dominio;

namespace Music.Web.Controllers
{
    public class ArtistaController : Controller
    {
        ArtistaDao artistaDao = new ArtistaDao();
        // GET: Artista
        public ActionResult Index()
        {
            var artista = artistaDao.BuscarTodos();

            return View(artista);
        }

        public ActionResult Adicionar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Adicionar(Artista artista)
        {
            if (! string.IsNullOrEmpty(artista.Nome))
            {
                artistaDao.Salvar(artista);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Index");
            }

        }

        public ActionResult Editar(int id)
        {

            var artista = artistaDao.BuscarPorId(id);

            return View(artista);

        }
        [HttpPost]
        public ActionResult Editar(Artista artista)
        {
            if (!string.IsNullOrEmpty(artista.Nome))
            {
                artistaDao.SalvarAlteracao(artista);

                return RedirectToAction("Index");
            }

            return View(artista);
        }

        //Método para excluir uma artista
        [HttpPost]
        public void Deletar(int id)
        {
            try
            {
                bool TrueOrFalse = artistaDao.Excluir(id);
                
            }
            catch (Exception)
            {

                throw;
            }
        }


    }
}

Music.Web/Controllers/ConsultaController.cs
using Music.Dominio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Music.Contexto;

namespace Music.Web.Controllers
{
    public class ConsultaController : Controller
    {
        ConsultaDao dao = new ConsultaDao();
        // GET: Consulta
        public ActionResult Index()
        {
            var query = dao.TipoConsulta();

            
            ViewBag.TipoConsulta = new SelectList(query, "ConsultaId", "Descricao");

            return View();
        }
        //Método para pesquisar 
        public ActionResult Pesquisar(int ConsultaId)
        {
           
            var query = dao.GetResultado(ConsultaId);
           
            

            return Json(query, JsonRequestBehavior.AllowGet);
        }

    }
}

Music.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Music.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Music.Web/Controllers/MusicasController.cs
using Music.Dominio;
using Music.Contexto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Music.Web.Controllers
{
    public class MusicasController : Controller
    {
        private MusicaDao dao = new MusicaDao();

        // GET: Musicas

        public ActionResult Index()
        {
            AlbumDao albumDao = new AlbumDao();
            ViewBag.Album = new SelectList(albumDao.BuscarTodos(), "AlbumId", "Titulo");
            return View();
        }

        public ActionResult Adicionar(int id)
        {
            //Pega o genero 
            GeneroDao gDao = new GeneroDao();
            //pega o tipo da midia
            TipoMidiaDao mDao = new TipoMidiaDao();
            //pega o album
            AlbumDao albumDao = new AlbumDao();

            //Busca o album selecionado na listagem
            var album = albumDao.BuscarPorId(id);


            ViewBag.IdAlbum = album.AlbumId;
            ViewBag.TituloAlbum = album.Titulo;


            var faixa = new Faixa();
            //Atribui o id do album a uma FK da Faixa
            faixa.AlbumId = album.AlbumId;

            ViewBag.GeneroID = new SelectList(gDao.BuscarTodos(), "GeneroID", "Nome");
            ViewBag.TipoMidiaId = new SelectList(mDao.BuscarTodos(), "TipoMidiaId","Nome");

            return View(faixa);
        }

        [HttpPost]
        public ActionResult Adicionar(Faixa faixa)
        {
            if (faixa.FaixaId == 0)
            {
                dao.Salvar(faixa);
                return RedirectToAction("Index");
            }
            else
            {
                return View(faixa);
            }

        }

        //Método para pesquisar as faixas de um determinado album
        public ActionResult Pesquisar(Faixa pesquisa)
        {
            
            var musicas = dao.Pesquisar(pesquisa);

            return Json(musicas, JsonRequestBehavior.AllowGet);
        }

        //Método para excluir um faixa
        [HttpPost]
        public void Deletar(int id)
        {
            try
            {
                bool TrueOrFalse = dao.Excluir(id);
            }
            catch (Exception)
            {

                throw;
            }
        }
        public ActionResult Editar(int id)
        {
            //Pega o genero 
            GeneroDao gDao = new GeneroDao();
            //pega o tipo da midia
            TipoMidiaDao mDao = new TipoMidiaDao();


            var faixa = dao.BuscarPorId(id);

            ViewBag.IdAlbum = faixa.AlbumId;// album.AlbumId;
            ViewBag.TituloAlbum = faixa.Album.Titulo; // album.Titulo;



            
            ViewBag.GeneroID = new SelectList(gDao.BuscarTodos(), "GeneroID", "Nome", faixa.GeneroId);
            ViewBag.TipoMidiaId = new SelectList(mDao.BuscarTodos(), "TipoMidiaId", "Nome", faixa.TipoMidiaId);

            return View(faixa);
        }

        [HttpPost]
        public ActionResult Editar(Faixa faixa)
        {
            if(faixa.FaixaId>0)
            {
                dao.SalvarAlteracao(faixa);
                return RedirectToAction("Index");
            }
           
            return View(faixa);
        }

    }
}

Music.Web/Views/Album/Adicionar.cshtml
@model Music.Contexto.Album
@{
    ViewBag.Title = "Adicionar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <div class="page-header page-header-loja">
        <h1 class="titulo-h1">Adicionando novo Album</h1>
    </div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.HiddenFor(model => model.AlbumId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.HiddenFor(model => model.AlbumId, new { htmlAttributes = new { @class = "form-control" } })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ArtistaId, htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            @Html.DropDownList("ArtistaID", null, "Selecione um Artista", new { @class = "form-control" })
        </div>

    </div>

    <div class="form-group">

        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-default" />
            <div class="btn btn-default">
                @Html.ActionLink("Voltar", "Index")
            </div>
        </div>

    </div>
    
</div>
}

Music.Web/Views/Album/Editar.cshtml
@model Music.Contexto.Album
@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="page-header page-header-loja">
            <h1 class="titulo-h1">Editando Album</h1>
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.AlbumId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.AlbumId, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ArtistaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ArtistaID")

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
                <div class="btn btn-default">
                    @Html.ActionLink("Voltar", "Index")
                </div>
            </div>

            
        </div>

    
    </div>

}

Music.Web/Views/Album/Index.cshtml
@model IEnumerable<Music.Contexto.Album>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header page-header-loja">
    <h1 class="titulo-h1">Listagem de Album</h1>
</div>


    @Html.ActionLink("Novo Album", "Adicionar",null,new{ @class = "btn btn-success" })


<table class="table table-responsive">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.AlbumId)</th>
            <th>@Html.DisplayNameFor(model => model.Titulo)</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AlbumId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    <a class="btn btn-default btn-xs" href="/Album/Editar/@item.AlbumId"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a> |
                    <a class="btn btn-danger btn-xs" onclick="Deletar(@item.AlbumId)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                  
                </td>
            </tr>
        }

    </tbody>
</table>



@section ScriptPage{

    <script src="~/Scripts/js/main.js"></script>
     <script src="~/Scripts/js/jsalbum.js"></script>

}

Music.Web/Views/Artista/Adicionar.cshtml
@model Music.Contexto.Artista
@{
    ViewBag.Title = "Adicionar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header page-header-loja">
    <h1 class="titulo-h1">Adicionando novo Artista</h1>
</div>
@using (Html.BeginForm())
{

    <div class="form-horizontal">
        <hr />
        
        
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
               
            </div>
        </div>
        
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-default" />
            <div class="btn btn-default">
                @Html.ActionLink("Voltar", "Index")
            </div>
        </div>

    </div>

}

Music.Web/Views/Artista/Editar.cshtml
@model Music.Contexto.Artista
@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="page-header page-header-loja">
            <h1 class="titulo-h1">Editando Artista</h1>
        </div>
        <hr />
       
        <div class="form-group">
            @Html.HiddenFor(model => model.ArtistaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ArtistaId, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
              
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
                <div class="btn btn-default">
                    @Html.ActionLink("Voltar", "Index")
                </div>
            </div>
        </div>
    </div>

}

Music.Web/Views/Artista/Index.cshtml
@model IEnumerable<Music.Contexto.Artista>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page-header page-header-loja">
    <h1 class="titulo-h1">Listgagem de Artistas</h1>
</div>

@Html.ActionLink("Novo Artista", "Adicionar", null, new { @class = "btn btn-success" })

<section class="secao-artista">
    <table class="table table-responsive">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.ArtistaId)</th>
                <th>@Html.DisplayNameFor(model => model.Nome)</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ArtistaId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>

                        <a class="btn btn-default btn-xs" href="/Artista/Editar/@item.ArtistaId"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a> |
                        <a class="btn btn-danger btn-xs" onclick="Deletar(@item.ArtistaId)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                        
                    </td>
                </tr>
            }

        </tbody>
    </table>

</section>

@section ScriptPage{

    <script src="~/Scripts/js/main.js"></script>
<script src="~/Scripts/js/jsartista.js"></script>

}

Music.Web/Views/Consulta/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header page-header-loja">
    <h1 class="titulo-h1">Consultas</h1>
</div>


<form class="form-inline">
    <div class="form-group">
        @Html.DropDownList("TipoConsulta", string.Empty)
    </div>
    <button type="button" id="pesquisar" class="btn btn-primary">Pesquisar</button>
</form>

<div class="row">
    <div id="resultado-consulta"></div>
</div>


@section ScriptPage{

    <script src="~/Scripts/js/jsconsulta.js"></script>

}

Music.Web/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>
    <img id="foto"/>
</div>




@section ScriptPage{

    <script src="~/Scripts/js/main.js"></script>


    }

Music.Web/Views/Musicas/Adicionar.cshtml
@model Music.Contexto.Faixa
@{
    ViewBag.Title = "Adicionar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<<div class="page-header page-header-loja">
    <h1 class="titulo-h1">Adisiconando nova Música</h1>
</div>

<div row>

    @using (Html.BeginForm())
    {

        <div class="form-horizontal">
            <hr />
            <div class="form-group">
                @Html.HiddenFor(model => model.FaixaId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.FaixaId, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            @* Album *@
            <div class="form-group">
                @Html.HiddenFor(model => model.AlbumId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.HiddenFor(model =>model.AlbumId, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Título Album", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input id="titulo-album-desativado" class="form-control" value="@ViewBag.TituloAlbum" />
                </div>
            </div>

            @* TipoMidia *@
            <div class="form-group">
              @Html.LabelFor(model=>model.TipoMidiaId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.DropDownList("TipoMidiaId", string.Empty)
                </div>

            </div>

            @* Genero *@
            <div class="form-group">
                @Html.LabelFor(model=>model.GeneroId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.DropDownList("GeneroID", string.Empty)
                </div>

            </div>
            <div class="form-group">
                @Html.Label("Compositor", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Compositor, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            <div class="form-group">
                @Html.Label("Milissegundos", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.Milissegundos, new { htmlAttributes = new { @class = "form-control", type="number" } })

                </div>
            </div>

            <div class="form-group">
                @Html.Label("Bytes", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.Bytes, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Preço Unitário", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.PrecoUnitario, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
                <div class="btn btn-default">
                    @Html.ActionLink("Voltar", "Index")
                </div>
            </div>

        </div>

    }
</div>

@section ScriptPage{
    <script src="~/Scripts/js/jsmuscia.js"></script>
}

Music.Web/Views/Musicas/Editar.cshtml
@model Music.Contexto.Faixa
@{
    ViewBag.Title = "Adicionar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<<div class="page-header page-header-loja">
    <h1 class="titulo-h1">Editando Música</h1>
</div>

<div row>

    @using (Html.BeginForm())
    {

        <div class="form-horizontal">
            <hr />
            <div class="form-group">
                @Html.HiddenFor(model => model.FaixaId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.FaixaId, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            @* Album *@
            <div class="form-group">
                @Html.HiddenFor(model => model.AlbumId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.AlbumId, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Título Album", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input id="titulo-album-desativado" class="form-control" value="@ViewBag.TituloAlbum" />
                </div>
            </div>

            @* TipoMidia *@
            <div class="form-group">
                @Html.LabelFor(model => model.TipoMidiaId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.DropDownList("TipoMidiaId", string.Empty)
                </div>

            </div>

            @* Genero *@
            <div class="form-group">
                @Html.LabelFor(model => model.GeneroId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.DropDownList("GeneroID", string.Empty)
                </div>

            </div>
            <div class="form-group">
                @Html.Label("Compositor", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Compositor, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
            <div class="form-group">
                @Html.Label("Milissegundos", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.Milissegundos, new { htmlAttributes = new { @class = "form-control", type = "number" } })

                </div>
            </div>

            <div class="form-group">
                @Html.Label("Bytes", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.Bytes, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Preço Unitário", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.PrecoUnitario, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
                <div class="btn btn-default">
                    @Html.ActionLink("Voltar", "Index")
                </div>
            </div>

        </div>

    }
</div>

@section ScriptPage{
    <script src="~/Scripts/js/jsmuscia.js"></script>
}

Music.Web/Views/Musicas/Index.cshtml
@model Music.Contexto.Album
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page-header page-header-loja">
    <h1 class="titulo-h1">Listagem de Músicas</h1>
</div>

<form class="form-inline">
    <div class="form-group">
          @Html.DropDownList("Album", null, "Selecione um Album", new { @class = "form-control" })
    </div>
    <button type="button" id="pesquisar" class="btn btn-primary">Pesquisar</button>

    @Html.ActionLink("Nova Musica", "Adicionar", null, new { @class = "btn btn-success", id = "new-music" })

</form>


<table id="secao-pesquisa" class="table">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nome da Música</th>
            <th>Gênero</th>
            <th>Preço</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody id="resultados"></tbody>
</table>

@section ScriptPage{

    <script src="~/Scripts/js/jsmuscia.js"></script>

}

Music.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title</title>
    
    <link rel="stylesheet" href="@Url.Content("~/Content/bootstrap.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/css/estilos.css")" />
   
    @RenderSection("styles", false)

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Music Collection", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Album", "Index", "Album")</li>
                    <li>@Html.ActionLink("Artistas", "Index", "Artista")</li>
                    <li>@Html.ActionLink("Musicas", "Index", "Musicas")</li>
                    <li>@Html.ActionLink("Consultas", "Index", "Consulta")</li>

                </ul>
            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
    </div>


    <script src="@Url.Content("~/Scripts/jquery-1.12.4.js")"></script>
    
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>

    @RenderSection("ScriptPage", false)
</body>


</html>